#pragma once
#define REN_FILE_VERSION_MAJOR 1
#define REN_FILE_VERSION_MINOR 37
#define REN_FILE_VERSION_BUILD 0
#define REN_FILE_VERSION_REVISION 1
#define REN_FILE_VERSION REN_FILE_VERSION_MAJOR, REN_FILE_VERSION_MINOR, REN_FILE_VERSION_BUILD, REN_FILE_VERSION_REVISION
