include(FetchContent)
set(LIBTYPE STATIC)
set(ALSOFT_UTILS OFF)
set(ALSOFT_EXAMPLES OFF)
set(ALSOFT_TESTS OFF)
set(ALSOFT_INSTALL OFF)
set(ALSOFT_UPDATE_BUILD_VERSION OFF)
set(ALSOFT_ENABLE_MODULES OFF)
set(ALSOFT_BACKEND_WASAPI OFF)
set(ALSOFT_BACKEND_DSOUND OFF)
set(ALSOFT_BACKEND_WINMM OFF)
set(ALSOFT_BACKEND_WAVE OFF)
set(ALSOFT_EAX ON)
FetchContent_Declare(OpenALSoft
    URL https://github.com/kcat/openal-soft/archive/83ea7236c6f23fc98e2b62eb9c5b3abfd4b2be86.tar.gz
    URL_HASH SHA256=93ba6f107e8864d0f62555b8031f40bb9710739fb010a98fb341d2d5ef092ed8)
FetchContent_MakeAvailable(OpenALSoft)
if(MSVC)
    set_property(TARGET OpenAL PROPERTY MSVC_RUNTIME_CHECKS "")
    target_compile_options(OpenAL PRIVATE "$<$<CONFIG:Debug>:/O2>" "$<$<CONFIG:Debug>:/Ob2>")
else()
    target_compile_options(OpenAL PRIVATE "$<$<CONFIG:Debug>:-O2>")
endif()
