set(platform_sync_source "${CMAKE_CURRENT_LIST_DIR}/POSIX/Synchronization.cpp")
if(WIN32)
    set(platform_sync_source "${CMAKE_CURRENT_LIST_DIR}/Windows/Synchronization.cpp")
endif()
if(WIN32)
    set(platform_thread_id_source "${CMAKE_CURRENT_LIST_DIR}/Windows/ThreadId.cpp")
else()
    set(platform_thread_id_source "${CMAKE_CURRENT_LIST_DIR}/POSIX/ThreadId.cpp")
endif()
add_library(ren_sync STATIC "${platform_sync_source}" "${platform_thread_id_source}")
target_include_directories(ren_sync PUBLIC "${CMAKE_CURRENT_LIST_DIR}/..")
target_compile_features(ren_sync PUBLIC cxx_std_23)
if(NOT WIN32)
    find_package(Threads REQUIRED)
    target_link_libraries(ren_sync PUBLIC Threads::Threads)
endif()
