# Run from a VC6 developer command prompt (VCVARS32.BAT).
if(NOT CMAKE_HOST_WIN32)
    message(FATAL_ERROR "The VC6 toolchain must run on Windows.")
endif()
find_program(REN_VC6_CL NAMES cl REQUIRED)
find_program(REN_VC6_LINK NAMES link REQUIRED)
find_program(REN_VC6_LIB NAMES lib REQUIRED)
find_program(REN_VC6_RC NAMES rc REQUIRED)
find_program(REN_VC6_NMAKE NAMES nmake REQUIRED)
set(CMAKE_C_COMPILER "${REN_VC6_CL}" CACHE FILEPATH "VC6 C compiler")
set(CMAKE_CXX_COMPILER "${REN_VC6_CL}" CACHE FILEPATH "VC6 C++ compiler")
set(CMAKE_LINKER "${REN_VC6_LINK}" CACHE FILEPATH "VC6 linker")
set(CMAKE_AR "${REN_VC6_LIB}" CACHE FILEPATH "VC6 librarian")
set(CMAKE_RC_COMPILER "${REN_VC6_RC}" CACHE FILEPATH "Win32 resource compiler")
