function(ren_add_target name kind)
    set(sources ${REN_${name}_SOURCES})
    if(kind STREQUAL "WIN32")
        add_executable(${name} WIN32 ${sources})
    else()
        add_library(${name} ${kind} ${sources})
    endif()
    ren_target_settings(${name})
    target_link_libraries(${name} PRIVATE ren_platform)
    if(MSVC)
        target_compile_options(${name} PRIVATE "$<$<COMPILE_LANGUAGE:C,CXX>:/W3>")
        if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            target_compile_options(${name} PRIVATE "$<$<COMPILE_LANGUAGE:C,CXX>:/MP4>")
        endif()
    else()
        target_compile_options(${name} PRIVATE "$<$<COMPILE_LANGUAGE:C,CXX>:-Wall>")
    endif()
    target_compile_features(${name} PRIVATE cxx_std_23)
    if(WIN32)
        target_compile_definitions(${name} PRIVATE _CRT_SECURE_NO_WARNINGS _CRT_NONSTDC_NO_WARNINGS
            WINVER=0x0A00 _WIN32_WINNT=0x0A00)
    endif()
    target_compile_definitions(${name} PRIVATE
        REN_ENABLE_GAMESPY=$<BOOL:${REN_ENABLE_GAMESPY}>)
    if(kind STREQUAL "SHARED" OR kind STREQUAL "WIN32")
        if(MSVC)
            target_link_options(${name} PRIVATE /DEBUG)
        endif()
        set_target_properties(${name} PROPERTIES DEBUG_POSTFIX D)
    endif()
endfunction()

set(REN_CORE_LIBRARIES wwdebug wwlib wwmath wwutil wwbitpack wwsaveload scontrol)
foreach(name IN LISTS REN_CORE_LIBRARIES)
    ren_add_target(${name} STATIC)
endforeach()
target_include_directories(wwlib PRIVATE "${REN_REGEX_INCLUDE_DIR}")
if(NOT WIN32)
    target_link_libraries(wwlib PUBLIC Microsoft::DirectX-Headers)
endif()
if(NOT EXISTS "${REN_REGEX_INCLUDE_DIR}/gnu_regex.h")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/Generated")
    file(WRITE "${CMAKE_BINARY_DIR}/Generated/gnu_regex.h" "#include \"regex.h\"\n")
    target_include_directories(wwlib PRIVATE "${CMAKE_BINARY_DIR}/Generated")
endif()
ren_add_target(scripts SHARED)
ren_add_target(bandtest STATIC)
set_target_properties(scripts PROPERTIES OUTPUT_NAME Scripts)
set_target_properties(bandtest PROPERTIES OUTPUT_NAME BandTest)
if(WIN32)
    target_link_libraries(scripts PRIVATE kernel32 user32 gdi32 winspool comdlg32 advapi32
        shell32 ole32 oleaut32 uuid odbc32 odbccp32)
    target_link_libraries(bandtest PRIVATE kernel32 ws2_32 winmm)
endif()
target_link_libraries(bandtest PRIVATE wwlib)
target_include_directories(bandtest PRIVATE
    "${PROJECT_SOURCE_DIR}/Code/wwlib" "${PROJECT_SOURCE_DIR}/Code/wwdebug")

# Only stage the DX8 headers. The old SDK also ships Windows headers such as
# basetsd.h that must not override the Windows SDK selected by Visual Studio.
set(directx_headers "${CMAKE_BINARY_DIR}/Generated/DirectX8")
file(MAKE_DIRECTORY "${directx_headers}")
set(dx8_headers
    d3d8.h
    d3d8caps.h
    d3d8types.h
    d3dx8.h
    d3dx8core.h
    d3dx8effect.h
    d3dx8math.h
    d3dx8math.inl
    d3dx8mesh.h
    d3dx8shape.h
    d3dx8tex.h
    dxfile.h)
foreach(filename IN LISTS dx8_headers)
    set(header "${REN_DIRECTX_INCLUDE_DIR}/${filename}")
    if(WIN32)
        configure_file("${header}" "${directx_headers}/${filename}" COPYONLY)
    else()
        file(READ "${header}" contents)
        string(ASCII 26 dos_eof)
        string(REPLACE "${dos_eof}" "" contents "${contents}")
        string(REPLACE "#include <objbase.h>" "#include \"Platform/Graphics/Types.h\"" contents "${contents}")
        string(REPLACE "#include <windows.h>" "" contents "${contents}")
        string(REPLACE "defined( _WIN32 ) && !defined( _NO_COM)" "!defined( _NO_COM)" contents "${contents}")
        string(REPLACE "PALETTEENTRY" "Platform::GraphicsPaletteEntry" contents "${contents}")
        string(REPLACE "HWND" "Platform::GraphicsWindowHandle" contents "${contents}")
        file(CONFIGURE OUTPUT "${directx_headers}/${filename}" CONTENT "${contents}" @ONLY)
    endif()
endforeach()
add_library(Vendor::dxguid INTERFACE IMPORTED GLOBAL)
if(WIN32)
    set_property(TARGET Vendor::dxguid PROPERTY INTERFACE_LINK_LIBRARIES dxguid)
endif()
add_library(Vendor::dsound INTERFACE IMPORTED GLOBAL)
if(WIN32)
    set_property(TARGET Vendor::dsound PROPERTY INTERFACE_LINK_LIBRARIES dsound)
endif()
if(REN_ENABLE_GAMESPY)
    get_filename_component(gamespy_parent "${REN_GAMESPY_HEADER_DIR}" DIRECTORY)
    ren_import_sdk(Vendor::GameSpy "${REN_GAMESPY_LIBRARY_RELEASE}" "${gamespy_parent}")
    set_target_properties(Vendor::GameSpy PROPERTIES
        IMPORTED_CONFIGURATIONS "Debug;Release"
        IMPORTED_LOCATION_DEBUG "${REN_GAMESPY_LIBRARY_DEBUG}"
        IMPORTED_LOCATION_RELEASE "${REN_GAMESPY_LIBRARY_RELEASE}")
endif()
set(REN_GAME_LIBRARIES wwnet ww3d2 wwphys wwaudio wwtranslatedb wwui combat binkmovie)
foreach(name IN LISTS REN_GAME_LIBRARIES)
    ren_add_target(${name} STATIC)
    target_link_libraries(${name} PRIVATE Vendor::d3dx8 Vendor::Miles)
endforeach()
target_link_libraries(binkmovie PRIVATE Vendor::BinkDecoder)
target_compile_definitions(combat PRIVATE "REN_SCRIPT_LIBRARY_NAME=\"$<TARGET_FILE_NAME:scripts>\"")
include(Platform/UI/Resources.cmake)
target_link_libraries(ww3d2 PRIVATE ren_graphics ren_fonts)
target_link_libraries(wwui PRIVATE ren_fonts)
target_link_libraries(ren_graphics PRIVATE Vendor::dxguid)
if(NOT WIN32)
    target_link_libraries(ren_graphics PUBLIC Microsoft::DirectX-Headers)
endif()
target_include_directories(binkmovie PRIVATE "${PROJECT_SOURCE_DIR}/Code/WWAudio")
ren_add_target(renegade WIN32)
set_target_properties(renegade PROPERTIES OUTPUT_NAME Renegade)
# Scripts is loaded at runtime; BandTest is linked statically.
add_dependencies(renegade scripts)
target_link_libraries(renegade PRIVATE ${REN_GAME_LIBRARIES} ${REN_CORE_LIBRARIES}
    bandtest Vendor::d3dx8 Vendor::dxguid Vendor::dsound Vendor::Miles)
if(WIN32)
    target_link_libraries(renegade PRIVATE dbghelp kernel32 user32 gdi32 winspool comdlg32 advapi32
        shell32 ole32 oleaut32 uuid winmm vfw32 wsock32 version)
endif()
if(REN_ENABLE_GAMESPY)
    target_link_libraries(renegade PRIVATE Vendor::GameSpy)
endif()
