function(ren_add_target name kind)
    set(sources ${REN_${name}_SOURCES})
    if(name STREQUAL "wwlib")
        list(APPEND sources "${REN_REGEX_SOURCE}")
    elseif(name STREQUAL "renegade" AND NOT REN_ENABLE_GAMESPY)
        list(REMOVE_ITEM sources "${PROJECT_SOURCE_DIR}/Code/Commando/GameSpy_QnR.cpp")
        list(APPEND sources "${PROJECT_SOURCE_DIR}/CMake/Stubs/GameSpyDisabled.cpp")
    endif()
    if(kind STREQUAL "WIN32")
        add_executable(${name} WIN32 ${sources})
    else()
        add_library(${name} ${kind} ${sources})
    endif()
    ren_target_settings(${name})
    target_link_libraries(${name} PRIVATE ren_platform)
    target_compile_options(${name} PRIVATE "$<$<COMPILE_LANGUAGE:C,CXX>:/W3>")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        target_compile_options(${name} PRIVATE "$<$<COMPILE_LANGUAGE:C,CXX>:/MP4>")
    endif()
    target_compile_features(${name} PRIVATE cxx_std_23)
    target_compile_definitions(${name} PRIVATE _CRT_SECURE_NO_WARNINGS _CRT_NONSTDC_NO_WARNINGS
        WINVER=0x0A00 _WIN32_WINNT=0x0A00)
    target_compile_definitions(${name} PRIVATE
        REN_ENABLE_GAMESPY=$<BOOL:${REN_ENABLE_GAMESPY}>)
    if(kind STREQUAL "SHARED" OR kind STREQUAL "WIN32")
        target_link_options(${name} PRIVATE /DEBUG)
        set_target_properties(${name} PROPERTIES DEBUG_POSTFIX D)
    endif()
endfunction()

set(REN_CORE_LIBRARIES wwdebug wwlib wwmath wwutil wwbitpack wwsaveload scontrol)
foreach(name IN LISTS REN_CORE_LIBRARIES)
    ren_add_target(${name} STATIC)
endforeach()
target_include_directories(wwlib PRIVATE "${REN_REGEX_INCLUDE_DIR}")
if(NOT EXISTS "${REN_REGEX_INCLUDE_DIR}/gnu_regex.h")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/Generated")
    file(WRITE "${CMAKE_BINARY_DIR}/Generated/gnu_regex.h" "#include \"regex.h\"\n")
    target_include_directories(wwlib PRIVATE "${CMAKE_BINARY_DIR}/Generated")
endif()
ren_add_target(scripts SHARED)
ren_add_target(bandtest STATIC)
set_target_properties(scripts PROPERTIES OUTPUT_NAME Scripts)
set_target_properties(bandtest PROPERTIES OUTPUT_NAME BandTest)
target_link_libraries(scripts PRIVATE kernel32 user32 gdi32 winspool comdlg32 advapi32
    shell32 ole32 oleaut32 uuid odbc32 odbccp32)
target_link_libraries(bandtest PRIVATE wwlib kernel32 ws2_32 winmm)
target_include_directories(bandtest PRIVATE
    "${PROJECT_SOURCE_DIR}/Code/wwlib" "${PROJECT_SOURCE_DIR}/Code/wwdebug")

# Only stage the DX8 headers. The old SDK also ships Windows headers such as
# basetsd.h that must not override the Windows SDK selected by Visual Studio.
set(directx_headers "${CMAKE_BINARY_DIR}/Generated/DirectX8")
file(MAKE_DIRECTORY "${directx_headers}")
file(GLOB dx8_headers "${REN_DIRECTX_INCLUDE_DIR}/d3d8*.h"
    "${REN_DIRECTX_INCLUDE_DIR}/dxfile.h" "${REN_DIRECTX_INCLUDE_DIR}/d3dx8*.h" "${REN_DIRECTX_INCLUDE_DIR}/d3dx8*.inl")
foreach(header IN LISTS dx8_headers)
    get_filename_component(filename "${header}" NAME)
    configure_file("${header}" "${directx_headers}/${filename}" COPYONLY)
endforeach()
add_library(Vendor::dxguid INTERFACE IMPORTED GLOBAL)
set_property(TARGET Vendor::dxguid PROPERTY INTERFACE_LINK_LIBRARIES dxguid)
add_library(Vendor::dsound INTERFACE IMPORTED GLOBAL)
set_property(TARGET Vendor::dsound PROPERTY INTERFACE_LINK_LIBRARIES dsound)
if(REN_ENABLE_GAMESPY)
    get_filename_component(gamespy_parent "${REN_GAMESPY_HEADER_DIR}" DIRECTORY)
    ren_import_sdk(Vendor::GameSpy "${REN_GAMESPY_LIBRARY_RELEASE}" "${gamespy_parent}")
    set_target_properties(Vendor::GameSpy PROPERTIES
        IMPORTED_CONFIGURATIONS "Debug;Release"
        IMPORTED_LOCATION_DEBUG "${REN_GAMESPY_LIBRARY_DEBUG}"
        IMPORTED_LOCATION_RELEASE "${REN_GAMESPY_LIBRARY_RELEASE}")
endif()
set(REN_GAME_LIBRARIES wwnet ww3d2 wwphys wwaudio wwtranslatedb wwui combat binkmovie)
foreach(name IN LISTS REN_GAME_LIBRARIES)
    ren_add_target(${name} STATIC)
    target_link_libraries(${name} PRIVATE Vendor::d3dx8 Vendor::Miles)
endforeach()
target_link_libraries(binkmovie PRIVATE Vendor::BinkDecoder)
target_link_libraries(ww3d2 PRIVATE ren_graphics)
target_link_libraries(ren_graphics PRIVATE Vendor::dxguid)
target_include_directories(binkmovie PRIVATE "${PROJECT_SOURCE_DIR}/Code/wwaudio")
ren_add_target(renegade WIN32)
set_target_properties(renegade PROPERTIES OUTPUT_NAME Renegade)
# Scripts is loaded at runtime; BandTest is linked statically.
add_dependencies(renegade scripts)
target_link_libraries(renegade PRIVATE ${REN_GAME_LIBRARIES} ${REN_CORE_LIBRARIES}
    bandtest dbghelp Vendor::d3dx8 Vendor::dxguid Vendor::dsound
    Vendor::Miles kernel32 user32 gdi32 winspool comdlg32 advapi32
    shell32 ole32 oleaut32 uuid winmm vfw32 wsock32 version)
if(REN_ENABLE_GAMESPY)
    target_link_libraries(renegade PRIVATE Vendor::GameSpy)
endif()
